U ichanges
PelagusWallet/pelagus-extension pull request #63
Opened 2023-09-13 19:13 UTC by DenisIvanov26

2023-09-13 20:08 UTC, wizeguyy reviewed
@jdowning100 will have to review this. This touches too much that I am not familiar enough with. I can at least say:

Please squash your commits into atomic changes with meaningful commit messages. No merge commits, please.

2023-09-13 20:09 UTC, wizeguyy requested changes, later dismissed
Please do not include merge commits.
Please make your commits atomic.

2023-09-14 16:57 UTC, jdowning100 commented
Hey @DenisIvanov26 @wizeguyy I noticed he squashed in my previously merged commit https://github.com/PelagusWallet/pelagus-extension/commit/ee8c11c0ed61ed9ba2ae4995b9e6ce2457f8bdba
Is this a problem?

2023-09-14 17:00 UTC, jdowning100 commented on ui/pages/Send.tsx
> +              // </div>
I would prefer you remove the comments tbh

2023-09-14 17:02 UTC, jdowning100 commented on ui/pages/SingleAsset.tsx
> +            {/* {localizedMainCurrencyAmount && (
Again just delete unused code, don't comment it out

2023-09-14 17:09 UTC, jdowning100 approved these changes
The code looks good. However I would like Clark, Mason and Raleigh to have a look at the wallet before we merge. I was under the impression that Raleigh wanted a black-on-white design instead of the current grey(ish)-on-blue.
Also, in the Add Custom Asset page the contract address label in the text box is greyed out.

2023-09-14 17:13 UTC, Denis2626 commented on ui/pages/Send.tsx
> +              // </div>
I think it is fine leaving them commented out as it will be easier to add the feature back once mainnet comes around

2023-09-14 20:08 UTC, robschleusner approved these changes

2023-09-14 21:15 UTC, merged