added button to clear tx history of address
PelagusWallet/pelagus-extension pull request #88
Opened 2023-09-25 20:18 UTC by DenisIvanov26

2023-09-26 15:01 UTC, robschleusner submitted a review, later dismissed

2023-09-26 17:31 UTC, jdowning100 requested changes
This doesn't seem to work on restart. I sent some transactions (external transactions, regular ones, token transfers) then cleared them. I restarted the wallet and about half transactions reappeared.

2023-09-27 18:52 UTC, robschleusner approved these changes

2023-09-27 20:42 UTC, jdowning100 commented on background/services/name/index.ts
> +      this.clearNameCacheEntry(chainId, address)
What does this do?

2023-09-27 21:06 UTC, DenisIvanov26 commented on background/services/name/index.ts
> +      this.clearNameCacheEntry(chainId, address)
Clears cache storage for the address

2023-09-27 21:33 UTC, jdowning100 approved these changes

2023-09-27 21:57 UTC, merged